$ANSIBLE_VAULT;1.1;AES256
61383238646534656264316534613463373161393636363134356137656163666236313938636431
3665343438616338653161626563636531363266306332380a636162616366396437373136323064
36666438663962353537636131313439363232396437333330623331356163623232663365336461
3735373236653465310a356532396536323430333266353231376265333035366539313663393563
34616531356465303965336565376631613739323438346533356436616336346438373564353764
62643261656431393861656331353832313431613565373964373432666461663434333963346664
39643636343339663338653338323536623137636536346266613737646531626362373035353631
37626165393365383962656533376338646665336334396230613334616666633639306630396131
33306339323863343861356665373930646439343764303562646631376434653136636337396564
61633035363730323232323938626364303839313038656632313161323162666363303961336464
61303830393535363338633633633932663863353563613830373532666332623630333030666236
62633438393462643261363039396265643839363366303862326365396637313361343561656464
6533
