$ANSIBLE_VAULT;1.1;AES256
36393836333433303437346366313039373638333132323131373830373439623938613431373233
3132643538613262363266363463653531653962313962340a643261623739366436616130313830
35353037333432396165373337646561323131363939383762326561613034326239613433633831
6465316664343462340a633238613262323861383836623636363764366633353237653466306136
61373431393262663534626632633934656139623535313166306666313339616532653637613336
38313334393062363165633965383731633239653665366462636365343538643835636665336339
35326638326632616666336439383739323465373138646631343530306461343062653831623861
30353033623836653862373939333937336438333964383165343431663062656561663164633763
62393633663835633063316632626139623334626634653766323830623630356338323638636365
33336339383662633061313130616236643935393932376639643263633661353863303366333530
30323565333036653732363865346164303736303639623637336333643463383764386431616230
37316563393139393461303863386133363465613535383230386132313464326236376532303732
66303238383737376266386236626434643430373936313766363864386631633434346433396537
3066373838323062326231623439393738363134316338623064
