$ANSIBLE_VAULT;1.1;AES256
34353564643137383830386264616432353438653436306262396535386531616337633534306161
3138363930346230363734613061363835616133383334360a626262383434333261393766633533
65396566363633626565626362613636396166636136646137346339353635303038663663613963
6136616336626336630a386262643436363930393834656331356665666166366238623132393764
63623539616663326562633463373832636530353636323762663637353666623265323565343431
32393861653530393237626531353837376434613430343265373431366637616461616661643061
66663836393234363366613666386265613366366135383332343763653061356237376366313961
37366264646136386335653130383130353265306135323330383964393865323238363134616530
30646336653762663633306632653736316532363930366266393332313062353266326430323537
66653630323465376638313936343932326166353161643866333236373333613937336332396262
61333036623833393262653566303331326664623235323263336136626666313332333235393132
36373366656535346365363133313433313663383634356138356664623838383430663336346337
65326434613932363931396166623336313831383835653937633661643538636138323065313330
3961353138343963633663653063303061633130313835386338
